nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['OPTIONS','POST', 'PUT', 'GET', 'DELETE', 'PATCH']
            max_age: 3600